### ISSUE TITLE
rename from Gittip to Gratipay

### ISSUE THREAD

**Issue by whit537** [daankortenbach/WP-Gittip#2]
Per https://medium.com/gratipay-blog/gratitude-gratipay-ef24ad5e41f9. :-)

**Comment by whit537** [comment]
Looks like this is done:

https://github.com/KakersUK/WP-Gratipay

**Comment by whit537** [comment]
I've updated the link in the Gratipay README in https://github.com/gratipay/gratipay.com/commit/a2f6ad9dd9f37ae844d174644c1ed26f6ce58078.

cc: @KakersUK

**Comment by KakersUK** [comment]
Awesome, many thanks!

**Comment by daankortenbach** [comment]
I'll archive this repo and redirect users on wp.org to new plugin, no need for it now.

**Comment by whit537** [comment]
:-)
